# Generated by Django 3.1.4 on 2021-02-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210203_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AddField(
            model_name='myuser',
            name='group',
            field=models.ManyToManyField(to='main.Student'),
        ),
    ]
