# Generated by Django 3.1.4 on 2021-02-03 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210203_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='days_eat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='clas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('students', models.ManyToManyField(to='main.Student')),
                ('teacher', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
