# Generated by Django 3.1.4 on 2021-02-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210203_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_change',
            field=models.DateField(auto_now=True),
        ),
    ]
