# Generated by Django 3.1.4 on 2021-02-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_student_date_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_change',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
