# Generated by Django 3.1.4 on 2021-02-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210203_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_change',
            field=models.DateField(auto_now=True),
        ),
    ]
