# Generated by Django 3.1.4 on 2021-02-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210204_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas',
            name='students',
            field=models.ManyToManyField(blank=True, to='main.Student'),
        ),
    ]
