# Generated by Django 3.1.4 on 2021-02-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210204_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='days_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='days_mounth',
            field=models.IntegerField(default=0),
        ),
    ]
